services:
  api:
    image: portfoliobalancerserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    networks: 
      - appnet
      
networks:
  appnet:
    name: appnet
    driver: bridge
