services:
  api:
    image: pbs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  appnet:
    name: appnet
    driver: bridge
